name: Checks

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  audit:
    name: NPM Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js v20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=critical --package-lock-only=true --registry=https://registry.npmjs.org
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js v20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: npm ci

      - name: Perform Production Build
        run: npm run build
